export const GET_ALL_FOOD_REQUEST ="GET_ALL_FOOD_REQUEST"
export const GET_ALL_FOOD_SUCCESS ="GET_ALL_FOOD_SUCCESS"
export const GET_ALL_FOOD_FAILURE ="GET_ALL_FODD_FAILURE"

export const SET_TOP_ORDERED_FOODS = "SET_TOP_ORDERED_FOODS"

export const GET_FILTERED_FOODS_SUCCESS = " GET_FILTERED_FOODS_SUCCESS"