export const GET_CATEGORY_REQUEST ="GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS ="GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_LAILURE ="GET_CATEGORY_LAILURE";


export const DELETE_CATEGORY_REQUEST ="DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS ="DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_LAILURE ="DELETE_CATEGORY_LAILURE";