
export const FIND_CART_REQUEST ="FIND_CART_REQUEST"
export const FIND_CART_SUCCESS ="FIND_CART_SUCCESS"
export const FIND_CART_FAILURE ="FIND_CART_FAILURE"

export const CLEARE_CART_REQUEST ="CLEARE_CART_REQUEST"
export const CLEARE_CART_SUCCESS ="CLEARE_CART_SUCCESS"
export const CLEARE_CART_FAILURE ="CLEARE_CART_FAILURE"

export const GET_ALL_CART_ITEMS_REQUEST ="GET_ALL_CART_ITEMS_REQUEST"
export const GET_ALL_CART_ITEMS_SUCCESS ="GET_ALL_CART_ITEMS_SUCCESS"
export const GET_ALL_CART_ITEMS_FAILURE ="GET_ALL_CART_ITEMS_FAILURE"

export const ADD_ITEM_TO_CART_REQUEST ="ADD_ITEM_TO_CART_REQUEST"
export const ADD_ITEM_TO_CART_SUCCESS ="ADD_ITEM_TO_CART_SUCCESS"
export const ADD_ITEM_TO_CART_FAILURE ="ADD_ITEM_TO_CART_FAILURE"

export const UPDATE_CADRITEM_REQUEST ="UPDATE_CADRITEM_REQUEST"
export const UPDATE_CADRITEM_SUCCESS ="UPDATE_CADRITEM_SUCCESS"
export const UPDATE_CADRITEM_FAILURE ="UPDATE_CADRITEM_FAILURE"

export const REMOVE_CADRITEM_REQUEST ="REMOVE_CADRITEM_REQUEST"
export const REMOVE_CADRITEM_SUCCESS ="REMOVE_CADRITEM_SUCCESS"
export const REMOVE_CADRITEM_FAILURE ="REMOVE_CADRITEM_FAILURE"